spring:
  profiles:
    active: dev
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/lzw?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8099

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.demo.entity
